name: rssreader
version: '0.1' 
summary: This is a rssreader snap application
description: |
  This is a rsssreader snap app which shows how to snap a click Qt app

grade: stable 
confinement: devmode

parts:
  qt-app:    
    source: https://github.com/liu-xiao-guo/rssreader.git
    plugin: qmake
    qt-version: qt5 
    prime:  
      - -usr/share/doc  
      - -usr/include  
    after: [desktop-ubuntu-app-platform]


